import { StyleSheet } from 'react-native';
import Colors from '../constants/Colors';

export default StyleSheet.create({
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
  },
  subheader: {
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 5,
  },
  intake: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  input: {
    flex: 1,
    height: 40,
    borderColor: Colors.lightgrey,
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    marginRight: 10,
    backgroundColor: Colors.white,
  },
  addButtonText: {
    color: Colors.white,
    fontWeight: 'bold',
  },
  buttonText: {
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  goBackButton: {
    position: 'absolute',
    bottom: 50,
    left: 20,
    right: 20,
    backgroundColor: Colors.purple,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
  },
  goBackButtonContainer: {
    backgroundColor: Colors.white,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 60,
  },
  greyGoBackButton: {
    backgroundColor: Colors.grey,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    width: '90%',
    alignSelf: 'center',
    marginBottom: 20,
  },
  // Log Display Styles
  logContainer: {
    flex: 1,
    padding: 20,
  },
  logContent: {
    flex: 1,
    paddingBottom: 10,
  },
  loadingText: {
    fontSize: 16,
    textAlign: 'center',
    color: Colors.grey,
  },
  noLogsText: {
    fontSize: 16,
    textAlign: 'center',
    color: Colors.grey,
  },
  dateSection: {
    marginBottom: 20,
    width: '100%',
  },
  dateHeader: {
    padding: 15,
    borderRadius: 10,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    marginHorizontal: 10,
  },
  dateText: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.white,
  },
  summaryText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.black,
    marginTop: 5,
  },
  logItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.white,
    padding: 15,
    borderRadius: 10,
    marginHorizontal: 10,
    marginTop: 5,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  logText: {
    fontSize: 14,
    color: Colors.black,
    marginBottom: 5,
  },
  photoButton: {
    padding: 8,
    borderRadius: 5,
    marginTop: 5,
    alignItems: 'center',
  },
  deleteButton: {
    padding: 8,
    borderRadius: 5,
    marginLeft: 10,
  },
  deleteButtonText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  photoButtonText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  // Form Styles
  formContainer: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  formScrollContainer: {
    flexGrow: 1,
    padding: 20,
  },
  formHeader: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    color: Colors.black,
  },
  formInput: {
    height: 50,
    borderColor: Colors.lightgrey,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    marginBottom: 20,
    backgroundColor: Colors.white,
    fontSize: 16,
    color: Colors.black,
    placeholderTextColor: Colors.grey,
  },
  estimateButton: {
    backgroundColor: Colors.orange,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 20,
  },
  resultsContainer: {
    backgroundColor: Colors.white,
    padding: 20,
    borderRadius: 10,
    marginBottom: 20,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  resultText: {
    fontSize: 16,
    color: Colors.black,
    marginBottom: 10,
  },
  portionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 15,
  },
  portionText: {
    fontSize: 16,
    color: Colors.black,
    marginRight: 10,
  },
  portionButton: {
    backgroundColor: Colors.medorange,
    padding: 8,
    borderRadius: 5,
    flex: 1,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  activePortionButton: {
    backgroundColor: Colors.orange,
  },
  portionButtonText: {
    color: Colors.black,
    fontSize: 14,
  },
  sliderContainer: {
    marginVertical: 15,
  },
  adjustText: {
    fontSize: 16,
    color: Colors.black,
    marginBottom: 10,
  },
  slider: {
    width: '100%',
    height: 40,
  },
  formPhotoButton: {
    backgroundColor: Colors.orange,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginVertical: 15,
  },
  imagePreview: {
    width: '100%',
    height: 200,
    borderRadius: 10,
    marginTop: 10,
  },
  singleButtonContainer: {
    marginTop: 20,
  },
  formButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  largeCancelButton: {
    backgroundColor: Colors.grey,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    width: '100%',
  },
  largeCancelButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  cancelButton: {
    backgroundColor: Colors.grey,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    flex: 1,
    marginRight: 10,
  },
  cancelButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  submitButton: {
    backgroundColor: Colors.orange,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    flex: 1,
    marginLeft: 10,
  },
  loader: {
    marginVertical: 20,
  },
  // Exercise Form Styles
  label: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 5,
    color: Colors.black,
    paddingHorizontal: 20,
  },
  dropdownWrapper: {
    marginBottom: 15,
    zIndex: 1000,
    paddingHorizontal: 20,
  },
  dropdown: {
    backgroundColor: Colors.white,
    borderColor: Colors.lightgrey,
    borderRadius: 10,
    paddingHorizontal: 10,
    color: Colors.black,
  },
  dropdownContainer: {
    borderColor: Colors.lightgrey,
    borderRadius: 10,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginBottom: 15,
  },
  halfInput: {
    flex: 1,
    marginHorizontal: 5,
  },
  notesInput: {
    height: 80,
    textAlignVertical: 'top',
    borderRadius: 10,
    marginHorizontal: 20,
    backgroundColor: Colors.white,
    color: Colors.black,
  },
  progressContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 20,
  },
  progressBar: {
    height: 10,
    width: '90%',
    borderRadius: 5,
  },
  progressText: {
    marginTop: 10,
    fontSize: 16,
    color: Colors.grey,
  },
  stepContainer: {
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '90%',
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  settingLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.black,
  },
  photoContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 15,
    overflow: 'hidden',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
});
